version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: weblab3_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: weblab3_db
    ports:
      - "5432:5432"

    volumes:
      - ./postgres-data:/var/lib/postgresql/data